<WellnessHelpScreen>:
    BoxLayout:
        orientation: 'vertical'
        size_hint: (1, 1)  # Fill the entire screen

        canvas.before:
            Color:
                rgba: 0.1, 0.6, 0.8, 1  # Light blue background
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(50)
            canvas.before:
                Color:
                    rgba: 0.086, 0.341, 0.459, 1  # Dark blue banner
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "Wellness Help"
                font_size: '40sp'
                font_name: 'assets/font.ttf'
                bold: True
                color: 1, 1, 1, 1
                size_hint: (1, None)
                height: dp(50)
                halign: 'left'
                valign: 'middle'
                text_size: self.size
                padding_x: dp(10)

            BoxLayout:
                size_hint: None, None
                size: dp(40), dp(40)
                padding: dp(5)
                pos_hint: {'center_y': 0.5}
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1 # Dark blue circle
                    Ellipse:
                        size: self.size
                        pos: self.pos

                Button:
                    background_normal: ''
                    background_color: [0, 0, 0, 0]  # Fully transparent background
                    on_release: app.sm.current = 'home'
                    size_hint: None, None
                    size: dp(30), dp(30)
                    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                    Image:
                        source: 'assets/arrow-55-24.png'
                        center_x: self.parent.center_x
                        center_y: self.parent.center_y


        GridLayout:
            cols: 3
            padding: 20
            spacing: 12

            Button:
                id: outdoors
                text: 'Going\noutdoors'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Going Outdoors', 'Going outdoors can drastically improve your\nmental and physical health. Going for walks\nand being in nature has been linked\nto better cardiovascular health, increases\nin vitamin D, reducing anxiety and a lower\nrisk of developing depression.')

            Button:
                id: socialisation
                text: 'Social time'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Socialisation', 'Socialising can lead to people making new\nfriends, partners and finding new hobbies.\nIt also sharpens your mental and cognitive skills,\nas well as resulting in people being\ngenerally happier.')

            Button:
                id: work
                text: 'Uni Work'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Uni Work', 'Uni work is important as if you do not put in\nthe time and effort, you might fall behind and\nnot be able to pursue the career that you\nhave worked so hard for at uni. Good luck\nand keep studying :)')

            Button:
                id: hobby
                text: 'Hobby Time'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Hobby Time', 'Hobbies are super important for you as\nthey reduce your stress, improve your\nconcentration and increase your\nnatural creativity!')

            Button:
                id: diet
                text: 'Good Diet'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Good Diet', 'Getting a balanced diet of proteins, carbs\nand fats allow for a variety of different benefits\nincluding feeling more energised during the day,\nfaster muscle growth and repair, and balancing\nhormones in your body. A balanced diet is\nreally important for you to live\na happy and healthy life!')

            Button:
                id: exercise
                text: 'Exercise'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Exercise', 'Exercise is good for building up a strong\ncardiovascular system, decreases risk of major\nillnesses, increases the levels of endorphins\nin your body and helps keep your\nmuscles and bones stronger and healthier.')

            Button:
                id: sleep
                text: 'Good Sleep'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Good Sleep', 'Good sleep helps you to improve your\nattention and concentration. It keeps you feeling\nrefreshed and alert during the day, as well as\nkeeping your immune system\nstrong.')

            Image:
                source: 'assets/logo3.png'

            Button:
                id: alcohol
                text: 'Alcohol\nModeration'
                font_name: 'assets/font.ttf'
                bold: True
                background_normal: ''
                background_color: 0.086, 0.341, 0.459, 1
                color: 1, 1, 1, 1
                border: (4, 4, 4, 4)
                canvas.before:
                    Color:
                        rgba: 0.1, 0.6, 0.8, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [10, 10, 10, 10]
                canvas.after:
                    Color:
                        rgba: 0.239, 0.514, 0.639, 1  # Medium blue border
                    Line:
                        width: 3
                        rounded_rectangle: [self.x, self.y, self.width, self.height, 10, 10, 10, 10]
                on_release: root.show_details('Alcohol Moderation', 'Alcohol Moderation is key as although drinking\nin moderation can help in social situations,\ndrinking in excess can lead to many health\nissues such as liver disease and strokes.')